# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/bear-classifier',
                'doc_host': 'https://eg9y.github.io',
                'git_url': 'https://github.com/eg9y/bear-classifier',
                'lib_path': 'bear_classifier'},
  'syms': {'bear_classifier.core': {'bear_classifier.core.foo': ('core.html#foo', 'bear_classifier/core.py')}}}